### ISSUE TITLE
Add privacy notice and t&cs to leu website

### ISSUE THREAD

**Issue by DavidRoy** [NERC-CEH/leu-app#10]
Create two new page on LEU website using attached files:
.../privacy-notice
.../terms-and-conditions

[European Ladybirds app privacy notice v20190214.docx](https://github.com/NERC-CEH/leu-app/files/2868485/European.Ladybirds.app.privacy.notice.v20190214.docx)
[LEU TC 2019 02 14.docx](https://github.com/NERC-CEH/leu-app/files/2868486/LEU.TC.2019.02.14.docx)

**Comment by BirenRathod** [comment]
@DavidRoy 
Both these pages have been created and placed at footer.

**Comment by DavidRoy** [comment]
thanks!
