### ISSUE TITLE
Drupal website for leu

### ISSUE THREAD

**Issue by DavidRoy** [NERC-CEH/leu-app#9]
Drupal 8 website required to support the European Ladybird App.  Domain name =
https://european-ladybirds.brc.ac.uk

To be hosted on Pantheon.

Requires the following menu structure:
1. Home page
2. Explore records
  a. Explore all records.  Indicia report page equivalent to https://www.brc.ac.uk/irecord/my-records
  b. Explore my records.  Indicia report page equivalent to https://www.brc.ac.uk/irecord/all-records
3. Survey Summary.  Indicia report page equivalent to 
4. Verify.  Indicia report page only available to those with role = verifier

**Comment by BirenRathod** [comment]
The test website has been setup to work on it.
here is the URL ->  http://test-euro-ladybird.pantheonsite.io

**Comment by kazlauskis** [comment]
When can we expect to have a live version of the site as well?

**Comment by BirenRathod** [comment]
We need at least some text and content to put on live.

**Comment by kazlauskis** [comment]
It is more about the app integration with the sites. Can we have a blank live page with the indicia api module on it?

**Comment by kazlauskis** [comment]
@BirenRathod Any thoughts on this?

**Comment by kazlauskis** [comment]
@DavidRoy @BirenRathod I am blocked by this at the moment. We have two drupal sites, one for test and one for dev, but these need further configuration to have Indicia API module installed and linked to some warehouse. Unfortunately, I do not have all the required permissions to do this myself. From my perspective, I just need a single (live) site to be all set up and ready to accept new user accounts and records coming in from the app. I could then link the app for initial testing period and release it, ie. I don't need the test and dev sites for the app development.

Apart from the list of requirements that David has listed at the top, to integrate the app it requires:

- A live drupal site under https://european-ladybirds.brc.ac.uk
- Linked to a warehouse where I have permissions to set up a survey, or else I can send you the survey specification
- Indicia API module installed and working

@BirenRathod I would like to do some planning of my work, could you give me some clearer timings when this could be set up?

**Comment by BirenRathod** [comment]
@kazlauskis 

- Use GitHub repository which you cloned on your machine to upload Indicia api module.
- After you upload module, please configure on this site http://dev-euro-ladybird.pantheonsite.io/ including to link warehouse setting.
- To link & test warehouse, you can setup the survey here : http://devwarehouse.indicia.org.uk 
- After you setup everything let me know I will push code to the  https://european-ladybirds.brc.ac.uk website. For live warehouse you can use this https://warehouse2.indicia.org.uk
- At this stage you don't need to worry about the test site, that is for people who are engaged, for them to see the result.

**Comment by kazlauskis** [comment]
Thanks, the dev site is pointing to http://warehouse2.indicia.org.uk/ at the moment. Are you saying we should change it to http://devwarehouse.indicia.org.uk instead?

I require to integrate the app to a backend site, this requires 'test' and 'live' sites, I don't mind what content it holds as long as the app can send the records to the sites and create/login user's.

**Comment by BirenRathod** [comment]
@kazlauskis 

To test the record, are you going to store record on Live warehouse or dev? if it is live, keep the setting as it is. 
You have already got account on warehouse2.indicia.org.uk. I have upgraded you as coreadmin, so you can able to create survey.

As you mentioned you need a test and live site, so we will stick with test site first. Please use this URL -> http://test-euro-ladybird.pantheonsite.io

Also, after you create survey & website in the warehouse, please change the settings in the indicia iform setting page on test site. Let me know once finish that setting, so I will take that on to live Drupal site.

**Comment by BirenRathod** [comment]
@kazlauskis 

Couple of things to consider....
1. Do not email me separately if you already putting issues here. I will get notified by GitHub issue or assigned it to me if I'm not in the list.
2. Everytime when you commit the code in the Pantheon ladybird GitHub repository, please do email me otherwise I won't be notify by Pantheon GitHub.

About Pantheon ladybird GitHub repostiory
After you committed code in the GitHub last time, It has gone into repository which was fine. After that I have updated Drupal core and it has failed for some reason, So to I had to restore the site from backup. Due to that I had to lost your commit. So, Could you please commit the Indicia API module again in the repository? This is one of the kind of problem occurred, so don't consider as ongoing things. Also, please email me after you commit.

**Comment by JimBacon** [comment]
Hi @kazlauskis. My ozone injury app stopped communicating with the Drupal site when it moved to Pantheon. My fix is at https://github.com/Indicia-Team/drupal-7-module-indicia-api/commit/abad7e7f49766b93787823c63839a3337688b8bc

**Comment by DavidRoy** [comment]
We decided to use warehouse1 for the European ladybird App.  

The main reason is so UK participants can retain their data in the same place.  The European App will replace the current iRecord ladybirds app

@BirenRathod I don't think I told you about this decision
@kazlauskis are you now able to go ahead with the Indicia setup?

**Comment by BirenRathod** [comment]
@DavidRoy, I'm not aware of that. 
@kazlauskis In that case, you don't need to do anything on warehouse2. But you still required to setup website and survey on warehouse1.

**Comment by BirenRathod** [comment]
@kazlauskis and link european ladybird website to warehouse1.

**Comment by kazlauskis** [comment]
@DavidRoy Yes, I can proceed with the set up now, thanks. I like the decision to replace the current app with the European one.

**Comment by BirenRathod** [comment]
Just for info this site https://european-ladybirds.brc.ac.uk is now live.

**Comment by kazlauskis** [comment]
Hi @BirenRathod, could you install the Indicia API module on live as well, this gives me the error here:
![screen shot 2018-11-25 at 19 17 11](https://user-images.githubusercontent.com/7383162/48983446-d3b81100-f0e6-11e8-8b5a-b1f8371e66a1.png)

**Comment by BirenRathod** [comment]
@kazlauskis 
Indicia API module has been installed now.

**Comment by kazlauskis** [comment]
I am seeing this issue when making requests through the site, any ideas how to fix it?
```
<div class="error">
  cUrl POST request failed. Please check cUrl is installed on the server and the $base_url setting is correct.<br/>
  URL:index.php/services/security/get_nonce<br/>
  Error number: 6<br/>
  Error message: Could not resolve host: index.php<br/>
  Server response<br/>
</div>
```

**Comment by BirenRathod** [comment]
@kazlauskis 

What request have you made? According to below message, cURL has already installed.
 
![image](https://user-images.githubusercontent.com/5941255/49367498-2e9fc880-f6e4-11e8-8e8d-1e186ec3600e.png)

**Comment by BirenRathod** [comment]
Hi Biren,

This is the request I was making where the issue shows up. This might be $base_url missing or something. Here is a similar issue reported:
https://forums.nbn.org.uk/viewtopic.php?id=4470


curl -X GET \
  https://european-ladybirds.brc.ac.uk/api/v1/users/test@test.com \
  -H 'Authorization: Basic dGVzdEB0ZXN0LmNvbTp0ZXN0' \
  -H 'Postman-Token: f546800a-052e-4f72-b1e5-e566eeae8e61' \
  -H 'cache-control: no-cache' \
  -H ‘x-api-key: yicnvjBCKXEPeRIfZNObxSaYp43ormMJ8zVHUs92'

Thanks,
Karolis

**Comment by BirenRathod** [comment]
@kazlauskis 

Thanks for the response. That forum bit is not helpful at all.

Anyway I need to debug that problem and find out it. Seems like the error relate to $base_url is coming from helper_base.php. This page hasn’t got warehouse URL in it and your api getting URL from there instead of database. Bit odd.

I have implemented a code in helper_config.php and added $base_url, see if that makes different.

**Comment by DavidRoy** [comment]
@BirenRathod The website is looking good, thanks

I have setup an account ok, but two changes are needed.
1. Once registered, the user should not be able to untick the 'I have read the T&Cs'
2. I do not see a 'My records' menu item when logged in.

**Comment by BirenRathod** [comment]
@DavidRoy 

 1. This is now invisible from user own profile.
 2. user can see "My records" link after logged in.

**Comment by DavidRoy** [comment]
@BirenRathod Thanks for fixing the above.  Remaining things are:
1. Create new menu item called 'Results'
2. Move 'My records' as sub-menu of 'Results'
3. Add 'All records' as new sub-menu of 'Results'
4. Add 'Survey summary' as new sub-menu of 'Results'
5. New page 'Survey summary'.  Indicia report page equivalent to https://www.brc.ac.uk/irecord/ladybird-app-summary but the map should show layers as location_type = 'NUTS Level 1'
6. New page 'Verify' for those with role = verifier.  Same system as for iRecord but limited to euro ladybird website (115)

**Comment by BirenRathod** [comment]
@DavidRoy 
I hove now completed following tasks.
1. New 'Results' item created.
2. 2,3,4,5. 'My records', 'All records' & 'survey summary' pages and menu items created and placed under 'Reports' sub menu.
6. Verify page is not required at present as this could be accessible via iRecord verification page.

**Note :** you have mentioned to use location_type = 'NUTS Level 1' which is not exist, so I have used 'NUTS level 2' but report doesn't show any records. Seems like report file doesn't recognise the european's locations.

**Comment by BirenRathod** [comment]
@DavidRoy 
Ignore my comment about doesn't show any records on survey summary page. it works fine.

**Comment by DavidRoy** [comment]
Thanks. Can you also work on the styling of the summary
![sum](https://user-images.githubusercontent.com/2699478/57940903-6468f000-78c5-11e9-8126-c3b2c4684eb7.png)

**Comment by DavidRoy** [comment]
All records report to exclude rejected and deleted records
